version: "3.8"

services:
  service_backend_fhyona_prod:
    container_name: service_backend_fhyona_prod
    build:
      target: production
      context: .
      args:
        - PORT=${PORT:-5555}
    ports:
      - "${PORT:-5555}:${PORT:-5555}"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512m"
        reservations:
          cpus: "0.25"
          memory: "256m"

  service_backend_fhyona_dev:
    container_name: service_backend_fhyona_dev
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT:-5555}
    ports:
      - "${PORT:-5555}:${PORT:-5555}"
      - "9229:9229"
    volumes:
      - .:/app
      - node_modules:/app/node_modules/
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512m"
        reservations:
          cpus: "0.25"
          memory: "256m"

volumes:
  node_modules:
