export enum TypeDocument {
  DNI = 'DNI',
  RUC = 'RUC',
  PASSPORT = 'PASAPORTE',
  FOREIGNERCARD = 'CARNÉ DE EXTRANJERIA',
  LICENSE = 'LICENCIA DE CONDUCIR',
  IDENTITYCARD = 'CÉDULA DE IDENTIDAD'
}